In [1]:
from sklearn import linear_model
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

In [2]:
df = pd.read_csv('data/tmdb_5000_movies.csv.gz') #https://www.kaggle.com/tmdb/tmdb-movie-metadata
df.dropna(inplace=True)
df.budget = df.budget/1000000
df.revenue = df.revenue/1000000

In [3]:
df.head(2)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237.0,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787.965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300.0,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961.000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500

In [4]:
df.describe()

,budget,id,popularity,revenue,runtime,vote_average,vote_count
count,1493.000000,1493.000000,1493.000000,1493.000000,1493.000000,1493.000000,1493.000000
mean,45.895338,65498.552579,35.749280,155.008339,108.657736,6.272873,1323.557267
std,53.692189,89841.824027,48.207525,240.871203,19.378758,0.970480,1792.459010
min,0.000000,11.000000,0.023681,0.000000,0.000000,0.000000,0.000000
25%,7.500000,8090.000000,11.624230,9.455232,95.000000,5.800000,207.000000
50%,27.000000,26320.000000,25.281197,62.548947,106.000000,6.300000,616.000000
75%,63.000000,76341.000000,45.149948,186.053725,120.000000,6.900000,1652.000000
max,380.000000,426469.000000,875.581305,2787.965087,201.000000,8.400000,13752.000000

In [5]:
predictors = ['budget','popularity','runtime','vote_average','vote_count']
X = df[predictors].values 
y = df['revenue'].values

In [6]:
#Split the data into train and validation (use random state for ability to reproduce results)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state=42)

In [7]:
# Model to try to predict the Revenue 
reg = linear_model.LinearRegression()
reg.fit(X_train,y_train) #Warning on MacOS can be ignored (or googled and then ignored)

/Users/mabbas/tf3/lib/python3.6/site-packages/scipy/linalg/basic.py:1226: RuntimeWarning: internal gelsd driver lwork query error, required iwork dimension not returned. This is likely the result of LAPACK bug 0038, fixed in LAPACK 3.2.2 (released July 21, 2010). Falling back to 'gelss' driver.
  warnings.warn(mesg, RuntimeWarning)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [8]:
y_pred = reg.predict(X_test)

In [9]:
#Inspect regression
print('Coefficients:')
for (p,v) in zip(predictors,np.round(reg.coef_,3)):
    print(p,v)
print('Intercept:', round(reg.intercept_,3))

# The mean squared error
print("\nMean squared error: %.2f" % np.sqrt(mean_squared_error(y_test, y_pred)))

# Explained variance score: 1 is perfect prediction
print('Variance score: %.2f' % r2_score(y_test, y_pred))

Coefficients:
budget 1.761
popularity 0.601
runtime 0.063
vote_average -6.088
vote_count 0.067
Intercept: -4.102

Mean squared error: 130.83
Variance score: 0.69